# Generated by Django 5.0.2 on 2024-02-10 16:47

import django.db.models.deletion
import fastfood_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastfood_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='food_images/')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('price', models.IntegerField(default=0)),
                ('valyuta', models.CharField(choices=fastfood_app.models.get_valyutas, default='som', max_length=5)),
                ('overal_rating', models.FloatField(default=0)),
                ('overal_rated_users', models.IntegerField(default=0)),
                ('adress_lat_a', models.FloatField(default=40.84116287658114)),
                ('adress_long_a', models.FloatField(default=72.32745981241342)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ManyToManyField(blank=True, to='fastfood_app.image')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
                ('adress_lat_a', models.FloatField(default=40.84411221242592)),
                ('adress_long_a', models.FloatField(default=72.33245510501874)),
                ('estimate_date', models.IntegerField(default=30)),
                ('delivered', models.BooleanField(default=False)),
                ('food_on_the_way', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fastfood_app.food')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(default=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='ratings',
            field=models.ManyToManyField(blank=True, to='fastfood_app.rate'),
        ),
    ]
