# Generated by Django 5.0.2 on 2024-02-10 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fastfood_app', '0002_image_food_order_rate_food_ratings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='adress_lat_a',
            new_name='address_lat_a',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='adress_long_a',
            new_name='address_long_a',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='adress_lat_a',
            new_name='address_lat_a',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='adress_long_a',
            new_name='address_long_a',
        ),
    ]
